### ISSUE TITLE
Remaining API Todo

### ISSUE THREAD

**Issue by danbelden** [danbelden/mercari-hacker-games-api#14]
Rank APIs
- [x] Add API to add rank (id, military_id, name, created)
- [x] Add API to list ranks by military_id

Rank Skill Recommendation APIs
- [ ] Add API to add skill recommendation to rank
- [ ] Add API to list skills recommended for a rank (Order by most popular skill?)

NLP
- [ ] Process skills using Google NLP API to assign categories
- [ ] Process Jobs using Google NLP API to assign categories
- [ ] Migrate search to use Google NLP categories as a filter instead of skillIds

Jobs
- [x] Add salary and location as properties of jobs (Add/Search endpoints need to be updated)
